---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - priorityclass.yaml
  - networkpolicy.yaml
  - networkpolicy-acr-refresher.yaml
  - serviceaccount-acr-refresher.yaml
  - secret-registry-credentials.yaml
  - cronjob-acr-token-refresh.yaml
  - plugin-container.yaml
  - rulesfile-official.yaml
  - rulesfile-custom.yaml
  - config.yaml
  - falco.yaml
